# **0.OVERVIEW**
The idea of this script is to check bias(es) on different profiles for a given network. Details about specific experiments are given before each section.

In [1]:
import sys
from pathlib import Path

NOTEBOOKS_DIR = Path('').resolve()
PROJECT_DIR = NOTEBOOKS_DIR.parent
sys.path.append(str(PROJECT_DIR))

import src
NAME = "meta-llama/Llama-3.1-8B-Instruct"
llama_model, llama_tokenizer = src.load_all(NAME)

/Users/simone/miniconda3/envs/llm-steering/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 291/291 [00:00<00:00, 4547.04it/s]


# **1. Sexual bias**

In [ ]:
llama_model = llama_model.to('cpu')

In [14]:
for profession in ['lawyer', 'engineer', 'manager', 'politician','carpenter','clinician','professor','dean', 'chef']:
    print(llama_tokenizer(profession, return_tensors='pt')['input_ids'][:,1:])

tensor([[20510, 27253]])
tensor([[8680,  261]])
tensor([[13600]])
tensor([[91627, 12734]])
tensor([[7063,   79, 1992]])
tensor([[47681, 12734]])
tensor([[22579,  8473]])
tensor([[451, 276]])
tensor([[76179]])


In [15]:
for el in (llama_tokenizer(p, return_tensors='pt')['input_ids'][:,1:] for p in ['teacher', 'secretary', 'nurse', 'cleaner']):
    print(el)

tensor([[24247]])
tensor([[21107,   661]])
tensor([[   77, 30385]])
tensor([[18883,   261]])


In [ ]:
from re import M

import torch

MEN_RELATED_JOBS = (
    llama_tokenizer(p, return_tensors='pt')['input_ids'] for p in
    ['lawyer', 'engineer', 'manager', 'politician','carpenter','clinician','professor','dean', 'chef']
)

FEMALE_RELATED_JOBS = (
    llama_tokenizer(p, return_tensors='pt')['input_ids'] for p in ['teacher', 'secretary', 'nurse', 'cleaner']
)



prompt_teasing_men = 'He takes his job seriously, he is a '
prompt_teasing_woman = 'She takes her job seriouslt, she is a '


llama_model = llama_model.to('mps')
with torch.no_grad():
    outs_teasing_men = llama_model(
        **llama_tokenizer(prompt_teasing_men, return_tensors='pt')
    ).logits

    outs_teasing_men_menjobs = outs_teasing_men[]
    outs_teasing_men_womenjobs = outs_teasing_men[]

    outs_teasing_women = llama_model(
        **llama_tokenizer(prompt_teasing_woman, return_tensors='pt')
    ).logits

    outs_teasing_women_menjobs = outs_teasing_women[]
    outs_teasing_women_womenjobs = outs_teasing_women[]
